### ISSUE TITLE
Render Crash

### ISSUE THREAD

**Issue by belucha** [belucha/oxyplot.blazor#3]
Error while Derserialize Null to number

```
2020-11-03 13:03:31.830 +01:00 [ERR] Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost Unhandled exception in circuit 'D1bpKNT1ZkEAHcpjY4tCzWpCSp_ejE1IuKpkqQhspm4'.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Double[]. Path: $[0] | LineNumber: 0 | BytePositionInLine: 5.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Double[]. Path: $[0] | LineNumber: 0 | BytePositionInLine: 5.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
   at System.Text.Json.Utf8JsonReader.GetDouble()
   at System.Text.Json.Serialization.Converters.JsonConverterDouble.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnReadEnumerable(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.AddNullToCollection(JsonPropertyInfo jsonPropertyInfo, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at OxyPlot.Blazor.JsInterop.GetBoundingClientRectAsync(ElementReference element, IJSRuntime JSRuntime) in D:\Projekte\GitLab\elotron\eloviz\blazor\oxyplot.blazor\OxyPlot.Blazor\JsInterop.cs:line 19
   at OxyPlot.Blazor.BlazorPlotView.UpdateSvgBoundingRect(Object _1, EventArgs _2) in D:\Projekte\GitLab\elotron\eloviz\blazor\oxyplot.blazor\OxyPlot.Blazor\BlazorPlotView.cs:line 71
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

**Comment by belucha** [comment]
getBoundingClientRect()
might return Null in some cases for some values, which causes deserialization problems
in blazor to double.json 
https://github.com/belucha/oxyplot.blazor/issues/3
see https://developer.mozilla.org/de/docs/Web/API/Element/getBoundingClientRect
System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
